name: ❓ Question (Other)
description: Use this for any other issues.
title: '[QUESTION] this_replace_with_title'
labels: ['question']
body:
    - type: checkboxes
      id: duplicates
      attributes:
          label: Prerequisites (Required)
          options:
              - label: I [searched for any existing report](https://github.com/itsmartashub/floristyle/issues?q=is%3Aissue) about this question to avoid opening a duplicate.
                required: true
              - label: This issue contains only one question.
                required: true
              - label: The title of this issue accurately describes the question.
                required: true

    - type: textarea
      attributes:
          label: What would you like to share? (Required)
          description: Provide a clear and concise explanation of your issue.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Additional information (Optional)
          description: Is there anything else I should know about this issue?
      validations:
          required: false

    - type: markdown
      attributes:
          value: |
              ### Thanks for using the Floristyle 🤝
